---
detectors:
  IrresponsibleModule:
    enabled: false

  LongParameterList:
    enabled: true
    exclude: []
    max_params: 4
    overrides:
      initialize:
        max_params: 5

  DataClump:
    max_copies: 3
    min_clump_size: 3

### Excluding directories

exclude_paths:
  - test/
  - config/
