name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run bundler-integrity check
        run: bundle exec bundler-integrity

      - name: Run Brakeman
        run: bundle exec brakeman

      - name: Run Bundle Audit
        run: bundle exec bundle-audit check --update

      - name: Run Importmap audit
        run: bundle exec bin/importmap audit
